name=input("Hello, What is your name? ")
print("\n")
age=int(input(f"Hi, {name}! How old are you? "))
print("\n")
print(f"Did you know that in five years you will be {age+5} years old?\nAnd five years ago you were {age-5}! Imagine that!")